name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.browser }} / Python ${{ matrix.python }} / Django ${{ matrix.django }} / 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
        django: ['>=3.2,<4.0','>=4.0,<4.1','>=4.1,<4.2','>=4.2,<5.0']
        browser: ['chrome', 'firefox']

    steps:
    - uses: actions/checkout@v2
    - name: Install Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install Chrome Webdriver
      if: ${{ matrix.browser == 'chrome' }}
      run: |
        python3 -m venv venv
        source venv/bin/activate

        pip install seleniumbase
        sudo apt-get install -y google-chrome-stable
        seleniumbase install chromedriver

        deactivate
        rm -rf venv
    - name: Install Firefox Webdriver
      if: ${{ matrix.browser == 'firefox' }}
      run: |
        python3 -m venv venv
        source venv/bin/activate

        sudo apt-get install -y firefox
        
        pip install seleniumbase
        seleniumbase install geckodriver

        deactivate
        rm -rf venv

    - name: Install Dependencies for Django ${{ matrix.django }}
      run: |
        pip install "Django${{ matrix.django }}"
        pip install -e .
        pip install -r requirements-dev.txt

    - name: Lint Python Code
      run: |
        black --check .
        isort --check-only --diff *.py django_selenium_test tests
    - name: Run Tests
      run: python tests/manage.py test
      env:
        SELENIUM_WEBDRIVER: ${{ matrix.browser }}